### ISSUE TITLE
Rendering issue in Firefox

### ISSUE THREAD

**Issue by misogl** [vacuumlabs/doc-viewer#1]
Titles don't fit.
![screenshot-2017-10-18 https we vacuumlabs com](https://user-images.githubusercontent.com/17564875/31729455-58e6d23a-b42f-11e7-87fb-20b266e3044a.png)

**Comment by hleumas** [comment]
@darjanin Can we improve this a little bit? Also, how do I get icons to work?

**Comment by darjanin** [comment]
@hleumas Icons required link to font-awesome css. I updated the visual. You can see it in open PR #2
